
- hosts:
  - openshift
  vars:
    version: openshift-origin-server-v3.9.0-191fece-linux-64bit
    path: "/home/build/{{ version }}/"
    oc_path: "{{ path }}oc"
    cluster_ip: 10.200.1.115
    project_name: "flowqe-test-project"
    service_account: flowqe
  roles:
    - { role: openshiftCluster, become: yes }
  # tasks:
  #   - name: Stop old cluster
  #     become: yes
  #     shell: "{{ oc_path }} cluster down"

  #   - name: Start Cluster
  #     become: yes
  #     shell: "{{ oc_path }} cluster up --public-hostname=\"{{ hostname }}\""

  #   - name: Login
  #     become: yes
  #     shell: "{{ oc_path }} login -u admin -p admin"



#     ./oc cluster up --public-hostname="10.200.1.106"
# ./oc login -u admin -p admin
# ./oc new-project flowqe-test-project
# ./oc adm policy add-cluster-role-to-user admin admin --config=/var/lib/origin/openshift.local.config/master/admin.kubeconfig
# ./oc adm policy add-cluster-role-to-user cluster-admin admin --config=/var/lib/origin/openshift.local.config/master/admin.kubeconfig
# ./oc adm policy add-cluster-role-to-user cluster-reader admin --config=/var/lib/origin/openshift.local.config/master/admin.kubeconfig

# ./oc create serviceaccount flowqe
# ./oc adm --config='/var/lib/origin/openshift.local.config/master/openshift-master.kubeconfig' policy add-cluster-role-to-user cluster-reader system:serviceaccount:flowqe-test-project:flowqe
# ./oc adm --config='/var/lib/origin/openshift.local.config/master/openshift-master.kubeconfig' policy add-cluster-role-to-user admin system:serviceaccount:flowqe-test-project:flowqe
# ./oc adm --config='/var/lib/origin/openshift.local.config/master/openshift-master.kubeconfig' policy add-cluster-role-to-user cluster-admin system:serviceaccount:flowqe-test-project:flowqe
# ./oc adm policy add-scc-to-user anyuid system:serviceaccount:flowqe-test-project:flowqe

# ./oc adm policy add-scc-to-user privileged -z system:serviceaccount:flowqe-test-project:flowqe
# ./oc adm policy add-scc-to-user restricted -z system:serviceaccount:flowqe-test-project:flowqe
# ./oc adm policy add-scc-to-user anyuid -z system:serviceaccount:flowqe-test-project:flowqe
# ./oc adm policy add-scc-to-user hostaccess -z system:serviceaccount:flowqe-test-project:flowqe
# ./oc adm policy add-scc-to-user hostmount-anyuid -z system:serviceaccount:flowqe-test-project:flowqe
# ./oc adm policy add-scc-to-user hostnetwork -z system:serviceaccount:flowqe-test-project:flowqe
# ./oc adm policy add-scc-to-user nonroot -z system:serviceaccount:flowqe-test-project:flowqe

# ./oc adm policy add-scc-to-group privileged system:authenticated
# ./oc adm policy add-scc-to-group restricted system:authenticated
# ./oc adm policy add-scc-to-group anyuid system:authenticated
# ./oc adm policy add-scc-to-group hostaccess system:authenticated
# ./oc adm policy add-scc-to-group hostmount-anyuid system:authenticated
# ./oc adm policy add-scc-to-group hostnetwork system:authenticated
# ./oc adm policy add-scc-to-group nonroot system:authenticated

# ./oc patch scc restricted --type=json -p '[{"op": "add", "path": "/allowHostDirVolumePlugin", "value": true}]'
# ./oc patch scc anyuid --type=json -p '[{"op": "add", "path": "/allowHostDirVolumePlugin", "value": true}]'
# ./oc patch scc hostnetwork --type=json -p '[{"op": "add", "path": "/allowHostDirVolumePlugin", "value": true}]'
# ./oc patch scc nonroot --type=json -p '[{"op": "add", "path": "/allowHostDirVolumePlugin", "value": true}]'

# ./oc adm policy add-scc-to-user hostnetwork -z flowqe
# ./oc create -f scc_admin.yaml


# groovy getToken.groovy > token.txt
