
- hosts:
  - openshift
  vars:
    version: openshift-origin-server-v1.5.1-7b451fc-linux-64bit
    path: "/home/build/{{ version }}/"
    oc_path: "{{ path }}oc"
    cluster_ip: 10.200.1.106
    project_name: "flowqe-test-project"
    service_account: flowqe
  roles:
    - { role: openshiftCluster, become: yes }
