version: '3'
services:
  electric-flow:
    image: "electricflow/efserver"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
      - "8200:8200"
    networks:
      - internal
    container_name: electricflow
    tty: true
networks:
  internal:
    driver: bridge
