version: '3'
services:
  electric-flow:
    image: "electricflow/efserver:latest"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
      - "8200:8200"
    networks:
      - internal
    container_name: electricflow
    tty: true
    extra_hosts:
      - maven.org:127.0.0.1
      - repo1.maven.org:127.0.0.1
      - jcenter.bintray.com:127.0.0.1

networks:
  internal:
    driver: bridge
